name: Lint and Deploy

on:
  push:
    branches:
      - main

jobs:
  lint-check:
    name: Check Code Quality (Lint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  deploy:
    name: Deploy to VPS
    # Điều kiện để chạy job này: `lint-check` phải thành công
    needs: lint-check
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.VPS_WORKDIR }}
            
            echo "--- Pulling latest code ---"
            git pull origin main
            
            echo "--- Installing dependencies on server ---"
            npm install --omit=dev
            
            echo "--- Restarting API server ---"
            pm2 restart api-server || pm2 start index.js --name api-server
